export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const SAVE_QUANTITY = "SAVE_QUANTITY";
export const UPDATE_QUANTITY = "UPDATE_QUANTITY";
